### ISSUE TITLE
Swift 2 println -> print

### ISSUE THREAD

**Issue by 24601** [ello/TimeAgoInWords#2]
Swift 2 doesn't like println, changing line 42 from println to print should fix this

**Comment by 24601** [comment]
Wait, already done, Podspec just doesn't seem to be updated? Will just use the git version in Podfile and it should work. Never mind....

**Comment by rynbyjn** [comment]
We should probably release an updated version. Thanks for the note!

**Comment by colinta** [comment]
I forgot you gave me & sean access!  Just pushed 2.0 - thanks!
